# name: Deploy Spring Boot to EC2
# on:
#   push:
#     branches:
#       - main
# jobs:
#   build-test-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#       - name: Build and Push Docker image
#         uses: docker/build-push-action@v2
#         with:
#           context: ./inspection-system-backend
#           push: true
#           tags: thearaseng/inspection-system-backend:${{ github.sha }}
#       - name: Deploy to EC2 instance
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USERNAME }}
#           key: ${{ secrets.EC2_PRIVATE_KEY }}
#           script: |
#             docker stop inspection-system-backend || true
#             docker rm inspection-system-backend || true
#             docker pull thearaseng/inspection-system-backend:${{ github.sha }}
#             docker run -d --name inspection-system-backend -p 8080:8080 thearaseng/inspection-system-backend:${{ github.sha }}